export const productspromotion = [
  {
    id: 1,
    title: 'Processador Intel Core i5-9400F Coffee Lake, Cache 9MB, 2.9GHz (4.1GHz Max Turbo), LGA 1151, Sem Vídeo',
    titlepromotion: 'Processador Intel Core i5-9400F Coffee Lake, Cache 9MB...',
    price: 899.90,
    description: 'Segurança e Confiabilidade- Novas instruções do Intel AES- Chave Segura- Extensões de guarda de software Intel (Intel SGX) com o Intel ME- Extensões de proteção de memória Intel (Intel MPX)- Protetor do Intel OS- Execute Desativar Bit- Protetor de inicialização Intel',
    img: 'https://images3.kabum.com.br/produtos/fotos/99683/processador-intel-core-i5-9400f-coffee-lake-cache-9mb-2-9ghz-4-1ghz-max-turbo-lga-1151-bx80684i59400f_processador-intel-core-i5-9400f-coffee-lake-cache-9mb-2-9ghz-4-1ghz-max-turbo-lga-1151-bx80684i59400f_1564429485_gg.jpg',
  },
  {
    id: 2,
    title: 'Placa-Mãe ASRock B450M Steel Legend, AMD AM4, mATX, DDR4',
    titlepromotion: 'Placa-Mãe ASRock B450M Steel Legend, AMD AM4, mATX, DDR4...',
    price: 749.90,
    description: 'Conteúdo da embalagem- 01 Placa-Mãe ASRock B450M Steel Legend- 01 Guia de instalação rápida- 01 CD de suporte, blindagem de E / S - 2 x cabos de dados SATA - 2 x parafusos para soquetes M.2',
    img: 'https://images2.kabum.com.br/produtos/fotos/100672/placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_1552586908_gg.jpg',
  },
  {
    id: 3,
    title: 'Placa de Vídeo MSI NVIDIA GeForce GTX 1050 Ti 4GT OC 4GB, GDDR5',
    titlepromotion: 'Placa de Vídeo MSI NVIDIA GeForce GTX 1050 Ti 4GT OC 4GB...',
    price: 929.90,
    description: 'Conectores:- 1x DVI-D- 1x HDMI (versão 2.0)- 1x DP (versão 1.4)- Suporta até 03 monitores - Resolução máxima digital: 7680 x 4320',
    img: 'https://images8.kabum.com.br/produtos/fotos/85798/85798_index_gg.jpg',
  },
];

export const products = [
  {
    id: 1,
    title: 'Processador Intel Core i5-9400F Coffee Lake, Cache 9MB, 2.9GHz (4.1GHz Max Turbo), LGA 1151, Sem Vídeo',
    titlepromotion: 'Processador Intel Core i5-9400F Coffee Lake, Cache 9MB...',
    price: 899.90,
    description: 'Segurança e Confiabilidade- Novas instruções do Intel AES- Chave Segura- Extensões de guarda de software Intel (Intel SGX) com o Intel ME- Extensões de proteção de memória Intel (Intel MPX)- Protetor do Intel OS- Execute Desativar Bit- Protetor de inicialização Intel',
    img: 'https://images3.kabum.com.br/produtos/fotos/99683/processador-intel-core-i5-9400f-coffee-lake-cache-9mb-2-9ghz-4-1ghz-max-turbo-lga-1151-bx80684i59400f_processador-intel-core-i5-9400f-coffee-lake-cache-9mb-2-9ghz-4-1ghz-max-turbo-lga-1151-bx80684i59400f_1564429485_gg.jpg',
  },
  {
    id: 2,
    title: 'Placa-Mãe ASRock B450M Steel Legend, AMD AM4, mATX, DDR4',
    titlepromotion: 'Placa-Mãe ASRock B450M Steel Legend, AMD AM4, mATX, DDR4...',
    price: 749.90,
    description: 'Conteúdo da embalagem- 01 Placa-Mãe ASRock B450M Steel Legend- 01 Guia de instalação rápida- 01 CD de suporte, blindagem de E / S - 2 x cabos de dados SATA - 2 x parafusos para soquetes M.2',
    img: 'https://images2.kabum.com.br/produtos/fotos/100672/placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_1552586908_gg.jpg',
  },
  {
    id: 3,
    title: 'Placa de Vídeo MSI NVIDIA GeForce GTX 1050 Ti 4GT OC 4GB, GDDR5',
    titlepromotion: 'Placa de Vídeo MSI NVIDIA GeForce GTX 1050 Ti 4GT OC 4GB...',
    price: 929.90,
    description: 'Conectores:- 1x DVI-D- 1x HDMI (versão 2.0)- 1x DP (versão 1.4)- Suporta até 03 monitores - Resolução máxima digital: 7680 x 4320',
    img: 'https://images8.kabum.com.br/produtos/fotos/85798/85798_index_gg.jpg',
  },
  {
    id: 4,
    title: 'SSD Kingston A400, 480GB, SATA, Leitura 500MB/s, Gravação 450MB/s - SA400S37/480G',
    titlepromotion: 'SSD Kingston A400, 480GB, SATA, Leitura 500MB/s, Gravação...',
    price: 389.90,
    description: 'Benefícios: - 10x mais rápido do que um disco rígido: Com incríveis velocidades de leitura/gravação, o SSD A400 não somente irá aumentar o desempenho, como também poderá ser usado para dar vida nova em computadores mais antigos. - Robusto: O A400 é resistente a impactos e vibrações, para confiabilidade reforçada em notebooks e outros dispositivos móveis. - Ideal para desktops e notebooks: A400 tem um formato de 7 mm parase ajustar auma grande variedade de computadores. É ideal para notebooks mais finos e computadores, ultrabooks e ultratop com espaço limitado.',
    img: 'https://images8.kabum.com.br/produtos/fotos/85198/85198_index_gg.jpg',
  },
  {
    id: 5,
    title: 'Monitor Gamer AOC HERO W-LED 27´ Widescreen, FHD, IPS, HDMI, DisplayPort, G-Sync Compatible, 144Hz, 1ms, Altura Ajustável - 27G2/BK',
    titlepromotion: 'Monitor Gamer AOC HERO W-LED 27´ Widescreen, FHD, IPS...',
    price: 1899.00,
    description: 'Destaques:</hr>- Gamer- Compatível com NVIDIA G-Sync- 144Hz- 1 ms- IPS- Design Premium',
    img: 'https://images1.kabum.com.br/produtos/fotos/111161/monitor-gamer-aoc-hero-w-led-27-widescreen-fhd-ips-hdmi-displayport-g-sync-compatible-144hz-1ms-altura-ajustavel-27g2-bk_1584370236_gg.jpg',
  },
  {
    id: 6,
    title: 'Memória XPG Spectrix D41 TUF, RGB, 8GB, 3000MHz, DDR4, CL16 - AX4U300038G16-SB41',
    titlepromotion: 'Memória XPG Spectrix D41 TUF, RGB, 8GB, 3000MHz, DDR4, CL16...',
    price: 289.90,
    description: 'Benefícios:* RGB lighting - suporta software dos principais fabricantes de placas-mãe, totalmente personalizável e programável* Design inspirado em armaduras com uma faixa LED RGB brilhante* Suporta a nova plataforma Intel X299 e implementa 2666MHz de linha de base (via configurações SPD)* Eficiência de energia superior: 20% menos consumo do que a DDR3 (a tensão de operação diminuiu de 1.5V para 1.2V)* Intel XMP 2.0 - overclocking mais acessível* Compatível com RoHS',
    img: 'https://images6.kabum.com.br/produtos/fotos/102746/memoria-adata-xpg-spectrix-d41-rgb-8gb-3000mhz-ddr4-cl16-ax4u300038g16-sb41_memoria-adata-xpg-spectrix-d41-rgb-8gb-3000mhz-ddr4-cl16-ax4u300038g16-sb41_1565358918_gg.jpg',
  },
  {
    id: 7,
    title: 'Cadeira Gamer PCTOP Azul',
    titlepromotion: 'Cadeira Gamer PCTOP Azul...',
    price: 799.00,
    description: 'Dimensões:- Largura do encosto: 53cm- Largura do assento: 37cm- Profundidade do assento: 52cm- Altura do encosto: 82cm- Altura do assento ajustável:28cm- Altura do chão ao braço:72 cm- Altura total: 125 cm',
    img: 'https://images0.kabum.com.br/produtos/fotos/133140/cadeira-gamer-pctop-azul-pc6022_1611349059_gg.jpg',
  },
  {
    id: 8,
    title: 'Notebook Lenovo Ideapad S145 Intel Core i5-8265U, 8GB, SSD 256GB, NVIDIA MX110 2GB, Windows 10, 15.6´, Prata',
    titlepromotion: 'Notebook Lenovo Ideapad S145 Intel Core i5-8265U, 8GB, SSD...',
    price: 3599.90,
    description: 'Especificações:- Processador: Intel Core i5-8265U (1.6GHz; 6MB Cache)- Sistema Operacional: Windows 10 Home- Tela: 15.6" HD (1366x768) Antirreflexo- Memória: 8GB (4GB soldado + 4GB slot DDR4 2400MHz)- Armazenamento: 256GB SSD- Unidade Ótica: Não incluso- Alto falante: Alto-falantes (2x 1.5W) com certificação Dolby Audio- Gráficos: NVIDIA GeForce MX110 com 2GB GDDR5- Bateria: 2 células - 35Wh- Bluetooth: Bluetooth 4.2- Outros: Câmera 0.3 MP',
    img: 'https://images7.kabum.com.br/produtos/fotos/115257/notebook-lenovo-ideapad-s145-intel-core-i5-8265u-8gb-ssd-256gb-nvidia-mx110-2gb-windows-10-15-6-prata-81s9000rbr_1596118908_gg.jpg',
  }, {
    id: 9,
    title: 'Headset Gamer HyperX Cloud Core, 7.1 Virtual Surround, Drivers 53mm',
    titlepromotion: 'Headset Gamer HyperX Cloud Core, 7.1 Virtual Surround, Drivers...',
    price: 449.90,
    description: 'Fone de ouvido:- Driver: dinâmico, 53 mm com magnetos de neodímio- Tipo: circumaural, fechado- Resposta de frequência: 15Hz–25.000 Hz- Impedância: 60 Ω- Nível de pressão sonora: 98 dBSPL/mW a 1 kHz- T.H.D.: < 2%- Potência de entrada classificação: 150mW, máxima 300mW- Comprimento do cabo: 1m- Tipo de conexão: Plugue de 3.5mm (4 polos)',
    img: 'https://images8.kabum.com.br/produtos/fotos/115318/headset-gamer-hyperx-cloud-core-7-1-virtual-surround-drivers-53mm-hx-hscc-2-bk-ww_1595258447_gg.jpg',
  }, {
    id: 10,
    title: 'Smartphone Samsung Galaxy A01, 32GB, 13MP, Tela 5.7´, Preto',
    titlepromotion: 'Smartphone Samsung Galaxy A01, 32GB, 13MP, Tela 5.7´, Preto...',
    price: 689.00,
    description: '- Velocidade do Processador: 2GHz, 1.45GHz - Resolução (Tela Principal): 720 x 1520 (HD+)  - Resolução - Câmeras Traseiras (Múltiplas): 13.0 MP + 2.0 MP  - Suporte ao Cartão de Memória: MicroSD (Up to 512GB)',
    img: 'https://images5.kabum.com.br/produtos/fotos/112685/smartphone-samsung-galaxy-a01-32gb-13mp-tela-5-7-preto-sm-a015mzkszto_1589313915_gg.jpg',
  }, {
    id: 11,
    title: 'Fonte Corsair CV650, 650W, 80 Plus Bronze',
    titlepromotion: 'Fonte Corsair CV650, 650W, 80 Plus Bronze...',
    price: 389.90,
    description: 'Especificações:- Potência: 650W- FAN: 120 mm- Comprimento: 125 mm- PFC Ativo- 80 Plus Bronze',
    img: 'https://images6.kabum.com.br/produtos/fotos/109696/fonte-corsair-cv650-650w-80-plus-bronze-cp-9020211-br_1580226089_gg.jpg',
  }, {
    id: 12,
    title: 'Mouse Gamer Redragon Cobra, 10000DPI, Chroma, Preto',
    titlepromotion: 'Mouse Gamer Redragon Cobra, 10000DPI, Chroma, Preto...',
    price: 139.90,
    description: 'Especificações:- Sensor PIXART PMW3325 para Alta Performance (10000 DPI/20G/100ips) (óptico)- Iluminação RGB Ajustável: Sistema de Iluminação Chroma RGB! (7 Diferentes Modos de Iluminação)- Polling Rate de 1000hz (Tempo de Resposta Ajustável via Software de 1/2/4/8ms)- 7 Botões Programáveis- Comprimento: 1.8 metros- Cabo de fibra trançada- 2 Botões Laterais para funções / atalhos, macros e etc',
    img: 'https://images5.kabum.com.br/produtos/fotos/94555/94555_1516707116_index_gg.jpg',
  }, {
    id: 13,
    title: 'Gabinete Gamer Cooler Master MasterCase Cosmos C700M, RGB, 4 Coolers, Lateral em Vidro',
    titlepromotion: 'Gabinete Gamer Cooler Master MasterCase Cosmos C700M, RGBs...',
    price: 3459.90,
    description: 'Especificações:- Dimensões: 650 (L) x 306 (L) x 651 (A) mm- Suporte para placa-mãe: Mini-ITX, Micro-ATX, ATX, E-ATX (Suporta até 12 "x 10,7")- Slots de expansão: 8- Baias de Drive - 5,25": 1- Baias de Drive - Combo de 3,5 "/ 2,5": 4 + 1 (na caixa de acessórios)- Baias de unidade - SSD: 4- Cooler da CPU suportado: 198 mm- Placa gráfica suportada: 490 mm (sem 3,5 "HDD BRK), 320 mm (com 3,5" HDD BRK)',
    img: 'https://images6.kabum.com.br/produtos/fotos/99686/gabinete-gamer-cooler-master-mastercase-cosmos-c700m-rgb-4-coolers-lateral-em-vidro-mcc-c700m-mg5n-s00__1547029494_gg.jpg',
  }, {
    id: 14,
    title: 'WaterCooler Corsair Hydro Series High Performance H45',
    titlepromotion: 'WaterCooler Corsair Hydro Series High Performance H45...',
    price: 269.90,
    description: 'Conteúdo da Embalagem: WaterCooler Corsair Hydro Series H45- Kit de montagem- Parafusos de montagem do ventilador e do radiador- Composto térmico (pré-aplicado)- Guia rápido',
    img: 'https://images0.kabum.com.br/produtos/fotos/78570/78570_index_gg.jpg',
  }, {
    id: 15,
    title: 'Multifuncional Brother Laser, Mono, 110V',
    titlepromotion: 'Multifuncional Brother Laser, Mono, 110V...',
    price: 3159.90,
    description: 'Especificações:- Velocidade da CPU (Processador): 800 MHz- Modo de Economia de Toner- Capacidade de Saída do Papel: 150 folhas- Funções de Segurança: Active Directory, Secure Function Lock, Bloqueio de Slot, Secure Print- Fonte de Alimentação: CA 110V 50 / 60Hz- Certificação Energy Star- Tela LCD: Touchscreen Colorido de 3.7"',
    img: 'https://images8.kabum.com.br/produtos/fotos/76128/76128_index_gg.jpg',
  }, {
    id: 16,
    title: 'Nobreak Senoidal SMS 3200VA Power Sinus Bivolt 27872',
    titlepromotion: 'Nobreak Senoidal SMS 3200VA Power Sinus Bivolt 27872...',
    price: 3999.90,
    description: 'Recursos:- Gerenciamento de Energia;- Gerenciamento de Missões Críticas;- Monitoramento Remoto;- Alarme Anti-intrusão;- Net Torpedo;- PC Remoto;- Vídeo ao Vivo via celular;- Localizador GPS via celular.',
    img: 'https://images1.kabum.com.br/produtos/fotos/72851/72851_index_gg.jpg',
  }, {
    id: 17,
    title: 'Smart TV 65´ 4K UHD LG, 3 HDMI, 2 USB, Bluetooth, Wi-Fi, HDR, ThinQ AI',
    titlepromotion: 'Smart TV 65´ 4K UHD LG, 3 HDMI, 2 USB, Bluetooth, Wi-Fi, HDR...',
    price: 4399.00,
    description: 'Geral:- Tamanho da tela: 65"- Resolução: 4K UHD- Tipo de Painel: LCD/LED- Processador: Quad Core Processor 4K',
    img: 'https://images0.kabum.com.br/produtos/fotos/130080/smart-tv-65-4k-uhd-lg-4-hdmi-2-usb-bluetooth-wi-fi-hdr-thinq-ai-65un7310psc_1603374275_gg.jpg',
  }, {
    id: 18,
    title: "Console Sony PlayStation 4 Mega Pack 15, 1TB, Horizon Zero Dawn Complete Edition + Marvel's Spider-Man + Ratchet & Clank",
    titlepromotion: 'Console Sony PlayStation 4 Mega Pack 15, 1TB, Horizon Zero...',
    price: 2599.90,
    description: 'Conteúdo da Embalagem:- Sistema PlayStation 4 (preto com 1 TB)- Controle DualShock 4 para PlayStation 4- Cabo HDMI- Cabo de alimentação- Headset mono com fio- Cabo USB para carregamento- Blu-Ray Disc do Horizon Zero Dawn Complete Edition* ++- Blu-Ray Disc do Edição Jogo do Ano de Marvel’s Spider-Man* +- Blu-Ray Disc do Ratchet & Clank (PS4)*- Voucher do PS Plus (3 meses)**',
    img: 'https://images3.kabum.com.br/produtos/fotos/129813/console-sony-playstation-4-mega-pack-15-1tb-horizon-zero-dawn-complete-edition-marvel-s-spider-man-ratchet-clank-cuh-2214b_1604691949_gg.jpg',
  }, {
    id: 19,
    title: 'Microfone Gamer HyperX QuadCast, Antivibração, LED, Preto e Vermelho',
    titlepromotion: 'Microfone Gamer HyperX QuadCast, Antivibração, LED, Preto...',
    price: 949.90,
    description: 'Microfone:- Consumo de Energia: 5V 125mA- Amostra/ Taxa bit: 48kHz/16-bit- Elemento: microfone condensador Electret- Tipo: três condensadores de 14mm- Padrão Polar: estéreo, omnidirecional, cardioide, bidirecional- Resposta de frequência: 20Hz–20kHz- Sensibilidade: -36dBV (1V/Pa, a 1kHz)- Comprimento do Cabo: 3m',
    img: 'https://images8.kabum.com.br/produtos/fotos/101288/101288_1554906159_index_gg.jpg',
  }, {
    id: 20,
    title: 'Roteador Wireless D-Link MU-MIMO Gigabit AC1200, 1200Mbps, 6 Antenas',
    titlepromotion: 'Roteador Wireless D-Link MU-MIMO Gigabit AC1200, 1200Mbps...',
    price: 339.90,
    description: 'Funcionalidades:- Assistente de configuração- Suporta IPv4 e IPv6- Gerenciamento Remoto- Servidor Virtual- DMZ (Demilitarized Zone)- Rede de Convidados (2,4 GHz + 5 GHz)- Dynamic DNS',
    img: 'https://images8.kabum.com.br/produtos/fotos/108308/roteador-wireless-d-link-mu-mimo-gigabit-ac1200-1200mbps-6-antenas-dir-846_1576181779_gg.jpg',
  },
];

export const productHar = [
  {
    id: 1,
    name: 'Hardware',
    subname: [
      { name: 'Coolers', id: 1 },
      { name: 'Disco Rigido', id: 2 },
      { name: 'Dirves', id: 3 },
      { name: 'Fontes', id: 4 },
      { name: 'Mémoria RAM', id: 5 },
      { name: 'Menu Rede', id: 6 },
      { name: 'Placa de Video', id: 7 },
      { name: 'Placas de som', id: 8 },
      { name: 'Placas-mãe', id: 9 },
      { name: 'Processadores', id: 10 },
      { name: 'Rede Wired(com fio)', id: 11 },
      { name: 'Rede wireless(sem fio)', id: 12 },
      { name: 'SSD', id: 13 },
      { name: 'Streamer', id: 14 },
      { name: 'Cachorro', id: 15 },
    ],
  },
  {
    id: 2,
    name: 'Gamer',
    subname: [
      { name: 'Cadeira Gamer', id: 1 },
      { name: 'Cockpit', id: 2 },
      { name: 'Consoles', id: 3 },
      { name: 'E-sports', id: 4 },
      { name: 'Geek', id: 5 },
      { name: 'Jogos', id: 6 },
      { name: 'Mesa Gamer', id: 7 },
      { name: 'Nintendo Switch', id: 8 },
      { name: 'PC', id: 9 },
      { name: 'Playstation 3', id: 10 },
      { name: 'Playstation 4', id: 11 },
      { name: 'Playstation 5', id: 12 },
      { name: 'Tapetes Gamer', id: 13 },
      { name: 'Tectoyr', id: 14 },
      { name: 'Xbox 360', id: 15 },
      { name: 'Xbox One', id: 16 },
      { name: 'Xbox Series', id: 17 },
    ],
  },
];
